### ISSUE TITLE
functionality/bug checklist

### ISSUE THREAD

**Issue by Algoprazolam** [Algoprazolam/Fallen-London-Fast-Travel#1]
- [x] doesn't work on initial load because travelbutton loads in late. can check against if null on travelbutton queryselector
- [x] checks for perhapsNot button too fast after redirecting to story
- [x] once opening a storylet the button gets disabled because it doesnt do a url change so should just check for if button is disabled
